### ISSUE TITLE
Peer-code-review with morning session team.

### ISSUE THREAD

**Issue by KingsleyIbe** [ReAliens/firstCapstone#3]
Hey @ReAliens, 

![image](https://user-images.githubusercontent.com/43799727/160290880-b377b4d6-2226-4887-b451-d629ebdad74f.png)

Great work on implementing the project. It looks great however, there are a few issues I want to draw your attention to:

- Some of your images are not displaying, It's good that you fix all broken images.
- Also, you could embed your live demo link in a text, this will make the project look neater.
- You could also consider centering your p elements in the 'Main program' section to have a better layout.

Great Job! 👍

**Comment by ReAliens** [comment]
thanks for your valuable review :heart:
